local avatar_asset_type_enum = Enum.AvatarAssetType
local avatar_accessory_type_enum = Enum.AccessoryType
return {
	[avatar_asset_type_enum.ShirtAccessory] = avatar_accessory_type_enum.Shirt;
	[avatar_asset_type_enum.PantsAccessory] = avatar_accessory_type_enum.Pants;
	[avatar_asset_type_enum.ShortsAccessory] = avatar_accessory_type_enum.Shorts;
	[avatar_asset_type_enum.TShirtAccessory] = avatar_accessory_type_enum.TShirt;
	[avatar_asset_type_enum.SweaterAccessory] = avatar_accessory_type_enum.Sweater;
	[avatar_asset_type_enum.JacketAccessory] = avatar_accessory_type_enum.Jacket;
	[avatar_asset_type_enum.DressSkirtAccessory] = avatar_accessory_type_enum.DressSkirt;
	[avatar_asset_type_enum.LeftShoeAccessory] = avatar_accessory_type_enum.LeftShoe;
	[avatar_asset_type_enum.RightShoeAccessory] = avatar_accessory_type_enum.RightShoe;
}
