return {
	BackAccessory = "BackAccessory";
	Face = "Face";
	FaceAccessory = "FaceAccessory";
	FrontAccessory = "FrontAccessory";
	TShirt = "GraphicTShirt";
	HairAccessory = "HairAccessory";
	Hat = "HatAccessory";
	NeckAccessory = "NeckAccessory";
	Pants = "Pants";
	Shirt = "Shirt";
	ShoulderAccessory = "ShouldersAccessory";
	Head = "Head";
	LeftArm = "LeftArm";
	LeftLeg = "LeftLeg";
	RightArm = "RightArm";
	RightLeg = "RightLeg";
	Torso = "Torso";
	WaistAccessory = "WaistAccessory";
	DynamicHead  = "Head"
}