return {
	asset_button = require("@self/AssetButton"),
	colour_wheel = require("@self/ColourWheel"),
	event_frames = require("@self/EventFrames"),
	asset_button_header = require("@self/AssetButtonHeader"),
	humanoid_viewport = require("@self/HumanoidViewport"),
	skin_brick_colour = require("@self/SkinBrickColour"),
	lune_ui = require("@self/lune_ui"),
	gizmo_transform = require("@self/GizmoTransform"),
	catalog_browser_tab_popup = require("@self/CatalogBrowserTabPopup"),
	button_header = require("@self/ButtonHeader")
}
